backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
media_folder: theme/assets/images
public_folder: /assets/images
collections:
  - name: pages
    label: Pages
    identifier_field: title
    extension: md
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    folder: cms/pages
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Layout
        widget: hidden
        name: layout
        default: '{{slug}}.html'
      - label: Seo
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: No index
            name: noindex
            widget: boolean
            default: false
            required: false
          - label: Open Graph Title
            name: og:title
            widget: string
            required: false
          - label: Open Graph Image
            name: og:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Twitter Title
            name: twitter:title
            widget: string
            default: summary
            required: false
          - label: Twitter Card
            name: twitter:card
            widget: string
            default: summary
            required: false
          - label: Twitter Site
            name: twitter:site
            widget: string
            required: false
          - label: Twitter Creator
            name: twitter:creator
            widget: string
            required: false
          - label: Additional HTML tags
            name: additional_tags
            widget: text
            required: false
  - label: Theme Settings
    name: settings
    identifier_field: title
    extension: json
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    files:
      - label: General
        name: site
        file: cms/_data/settings/site.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: General
          - hint: Full domain url (needed for a correct sitemap file)
            name: domain
            label: Domain
            widget: string
            required: false
          - name: favicon
            label: Favicon
            widget: image
            allow_multiple: false
            required: false
          - name: apple_touch_icon
            label: Apple Touch Icon
            widget: image
            allow_multiple: false
            required: false
          - name: header_additional_content
            label: Additional Content Header
            hint: Content here will be placed before </head> tag
            widget: text
            required: false
          - name: footer_additional_content
            label: Additional Content Footer
            hint: Content here will be placed before </body> tag
            widget: text
            required: false
          - name: images_optimization
            label: Images Optimization
            widget: object
            collapsed: false
            fields:
              - label: Image Formats
                name: formats
                widget: select
                multiple: true
                options:
                  - label: Avif
                    value: avif
                  - label: Webp
                    value: webp
              - label: Image Dimensions
                name: dimensions
                widget: select
                multiple: true
                options:
                  - label: '500'
                    value: 500
                  - label: '800'
                    value: 800
                  - label: '1080'
                    value: 1080
                  - label: '1600'
                    value: 1600
                  - label: '2000'
                    value: 2000
                  - label: '2600'
                    value: 2600
      - label: Colors
        name: colors
        file: cms/_data/colors.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Colors
      - label: Texts
        name: texts
        file: cms/_data/texts.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Texts
          - hint: "Original text: Our Sutton Suit in a fine-wale cord from Italy’s Duca Visconti mill is just one reason for you and your sweatpants to start dating other people.\_, key: 3a285bba"
            label: Text
            name: 3a285bba
            widget: text
          - hint: 'Original text: shop this look, key: 3a3d1e37'
            label: Text
            name: 3a3d1e37
            widget: string
          - hint: >-
              Original text: Lorem ipsum dolor sit amet, consectetur adipiscing
              elit, sed do eiusmod tempor incididunt ut labore et dolore magna
              aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
              laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
              dolor in reprehenderit in voluptate velit esse cillum dolore eu
              fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
              proident, sunt in culpa qui officia deserunt mollit anim id est
              laborum., key: 1e922a7c
            label: Text
            name: 1e922a7c
            widget: text
          - hint: 'Original text: SHOP, key: 26d2f6'
            label: Text
            name: 26d2f6
            widget: string
          - hint: 'Original text: The, key: 14851'
            label: Text
            name: '14851'
            widget: string
          - hint: 'Original text: Madison suit, key: 4f811914'
            label: Text
            name: 4f811914
            widget: string
          - hint: "Original text: Italian Donegal Tweed Madison Suit Jacket, Charcoal $548 BL028743\_Italian Donegal Tweed Madison Suit Trouser, Charcoal $298 PA1008743\_Pocket Sweatshirt, Salt And Pepper $98 KN918043\_, key: -6dce12a6"
            label: Text
            name: '-6dce12a6'
            widget: text
          - hint: 'Original text: soft jacket, key: 4b0f8984'
            label: Text
            name: 4b0f8984
            widget: string
          - hint: "Original text: Soft Italian Herringbone Sport Coat, Cream $698 BC032604\_Favorite Oxford Shirt, White $148 SH1229315\_Slim Fit Made in USA Jean, Riverside Wash, $268 JE039857\_, key: 3a2e241"
            label: Text
            name: 3a2e241
            widget: text
      - label: Links
        name: links
        file: cms/_data/links.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Links
          - hint: 'Original link: #, key: 23'
            label: Link
            name: '23'
            widget: string
          - hint: >-
              Original link:
              https://www.toddsnyder.com/products/heather-grey-flannel-traveler-suit-jacket-grey,
              key: -5eefb16a
            label: Link
            name: '-5eefb16a'
            widget: string
      - label: Images
        name: images
        file: cms/_data/images.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Images
          - label: Image
            name: 6e148e78
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '-637e9f33'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '-6faef3c4'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '-56abe7f1'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
publish_mode: editorial_workflow
